obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
#ifdef CONFIG_MACH_OPPO//ye.zhang@BSP.sensors, add for sensors ftm interface, 2014-10-31
obj-y += sensors_ftm.o
#endif
